Document: jdmc
Title: Debian jdmc Manual
Author: <insert document author here>
Abstract: This manual describes what jdmc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jdmc/jdmc.sgml.gz

Format: postscript
Files: /usr/share/doc/jdmc/jdmc.ps.gz

Format: text
Files: /usr/share/doc/jdmc/jdmc.text.gz

Format: HTML
Index: /usr/share/doc/jdmc/html/index.html
Files: /usr/share/doc/jdmc/html/*.html
