#!/bin/sh

STAGE_DIR=${1:-../debian}

LIBS="p2pmpi.jar log4j.jar"
APPS="bin/* " 

APP_DIR=usr/bin
LIB_DIR=usr/lib

mkdir -p $STAGE_DIR/$LIB_DIR
cp $LIBS $STAGE_DIR/$LIB_DIR

mkdir -p $STAGE_DIR/$APP_DIR
cp $APPS $STAGE_DIR/$APP_DIR

